
package com.momolela.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://publish.webservice.momolela.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://publish.webservice.momolela.com/", className = "com.momolela.webservice.server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://publish.webservice.momolela.com/", className = "com.momolela.webservice.server.SayHelloResponse")
    @Action(input = "http://publish.webservice.momolela.com/HelloServiceImpl/sayHelloRequest", output = "http://publish.webservice.momolela.com/HelloServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
